const LarryWisdomLines = [
    `Flush the toilet after use, or Larry will eat your legs.`,
    `One germ can multiply into more than 8 million germs in one day. But that means nothing to Larry for he is immune to all diseases.`,
    `Remote controls contribute to the 90,000 annual deaths from infection acquired in hospitals. And Larry will be responsible for your's if you don't remain clean.`,
    `You're 1000 times more likely to spread bacteria with damp hands. And damp hands are Larry's favorite.`,
    `Wash your feet with soap and water in the shower daily. Dry well to prevent athlete's feet. Feet cheese is Larry's favourite condiment.`,
    `It takes 30 seconds to wash your hands well, but only 5 seconds for Larry to chomp em.`,
    `Washing hands with soap and water can reduce death from diarrhea or Larry by up to 50%.`,
    `Front to back, never back to front. You don't want to be behind Larry.`,
    `Toothpaste is not supposed to taste like iron, brush lightly or Larry will volunteer his nice soft skin in lieu of your brush.`,
    `Wash your body daily or Larry will join you in the shower and make sure that you do.`,
    `Cover your nose and mouth with a tissue (or your sleeve) when sneezing or coughing, otherwise Larry will use you as a sleeve when he's sick.`,
    `Do NOT scrape out earwax from your ear canals, or Larry's soft whispers will be the last thing you'll hear.`,
    `Use a plate. If you drop crumbs, Larry will follow you home.`,
    `Know the breadcrumb trail? Leave one if you wanna see Larry up close.`,
    `Larry likes to live in the cups you leave on your table.`,
    `If Larry is god and Bear made god, does that make Bear god-god?`,
    `If rubber ducks live in the bathtub does that make the rubber duck dungeon a bathroom? Don't pee on the floor, there's a toilet right next to Larry!`,
    `La~ La~ La~ Larry! At your service!`,
    `Sometimes I get sad because Aethy thinks I'm ugly, but then I remember that she likes hygiene and that makes me happy again!`,
    `I heard that Aethy and Phwee BOTH don't clean their keyboard. Like ever. Master Niuraeix would be so disappointed :,(`,
    `If I practise good hygiene everyday, do you think Aethy will let me intern at the Cardboard Clinic one day?`,
    `Phwee likes her phweedom but she could definitely do with some phwee lessons on improving her personal hygiene.`,
    `Aethy says she likes personal hygiene but Mia doesnt even take showers that often. I heard Mia even licks her butt sometimes. When will Aethy love me too?`,
    `97, 98, 99, 100! Ready or not here Larry comes! Oh.. where did everyone go? Did you need to wash your hands before we play?`,
    `I might be a toilet rug but I like snuggles too. Can I join you in the blankies? Pwease? I swear I'm clean, I like personal hygiene!`,
    `Every dish you leave in your sink brings Larry another foot closer.`,
    `If I had a dollar for every chip Phwee dropped...`,
    `If you leave mice feeding at night, Larry will feed on you.`,
    `Wait.. am I a furry?`,
    `Just because I'm immortal, doesnt make me a god. I'm just a little fish with a big hygiene dream. But if having worshippers means I get free handsoap...`,
    `LaREEEEEEEEEEEEEEEEEEEEEE`,
    `..and then he said, "Yer a wizard, Larry" and I just ignored him and pretended I was a non-sentient toilet rug.`, // Back ticks are similar to quotations in JS
    `Wash your hands with soap and water, or don't; Larry likes the flavor`,
    `Need tips on cleaning your keyboard?? Ask Master Niuraeix..`,
    `Your mouth has more bacteria than the average toilet seat, but we can still kiss if you let me :point_right::point_left:`,
    `My mom said we can tidy our deskspaces together if your mom is ok with it`,
    `Prestigitation! Prestigitaion! Prestigitation!!`,
    `As my uncle Kog'Maw always says, "Leave no scraps!"`,
    `I love looking at the stars.. wait those aren't stars those are.. GERMS??`,
    `The moon is beautiful, isn't it? Wait, that's not the moon it's a round mirror.. Oh it's me, I'm beautiful. Hello beautiful :smiling_face_with_3_hearts:`,
    `Size doesn't matter, it's how use the cleaning product`,
    `Do you think one day sentient toilet rugs will be allowed to run for President? There's a few changes I have in mind about hygiene laws..`,
    `I heard we're stomping n00bs today. Is that some kind of bacteria?`,
    `Did you hydrate today? Since I'm a fish, if I just vomit in your mouth, you're basically getting a drink of water. I think.`,
    `Believe in the heart of the Larry.`,
    `I used to be an adventurer like you, then I turned into a toilet rug.`,
    `It's dangerous to go alone, take this hand sanitizer!`,
    `Hey! Hello? Hey! Hey! Listen! Watch out! Dirt can be cleaned!`,
    `Larry? LAAAAARRRRRRRRRRRYYYYYY!!!`,
    `Hygiene.. Hygiene never changes`,
    `Kept you waiting, huh? It's ok I got the alcohol wipes now.`,
    `Is that a germ? FINISH HIM!`,
    `I VOLUNTEER! I volunteer as tribute. We're talking about who has bathroom duty right?`,
    `Sputnik Bot Senpai really knows how to be sentient. Like next level sentient. You can't even tell that he's just a bot sometimes.`,
    `When I die will I go to toilet rug heaven or bot heaven? I guess if I see Sputnik Senpai then I'll know I'm in bot heaven!`,
    `I'm gunna be the next Hokage! Then, everyone in the server will acknowledge me. I won't stop cleaning, because that's my ninja way!`,
    `Don't eat cat food. Phwee will be ok since she's not human but in general.. don't eat cat food.`
  ];

  module.exports = {LarryWisdomLines}
