const rubberLarryPhrases = [
    "huh?",
    "ok.",
    "I think I get it.",
    "Why's that?",
    "interesting.",
    "yep",
    "gotcha :phweeNoted: ",
    "I see...",
    "makes sense :phweeNoted: ",
    "What do you mean by that?",
    "<a:aethySweat:985450674470944778>",
    "<:phweeHaha:951997660313841705>",
    "That's crazy.",
    "uh huh.",
    "keep going :phweeNoted:",
    "It's really hard to say.",
    "hmm",
    "God I hate my job- oh! Er, I mean.. you’re doing great human!",
    "Have you written tests for this case? :phweeQuestion:",
    "How do you do that? :phweeQuestion:",
    "What do you mean by that? :phweeQuestion:",
    "Makes sense",
    "Write it out, step by step, what do you want it to do?",
    "How long have you been stuck on this problem? Do you need a break?:phweeFLOwer:",
    "It’s great that you’ve worded this out, is there anything else?",
    "I'm sorry, I need more information about your problem. Can you tell me more?",
    "Is there a way to segregate the particular issue? :phweeQuestion:",
    "Tell me more please :miaBlankie:",
];

module.exports = { rubberLarryPhrases };
