module.exports.magicLines = [
  `It is certain.`,
  `It is decidedly so.`,
  `Without a doubt.`,
  `Yes, definitely.`,
  `You may rely on it.`,
  `As I see it, yes.`,
  `Most likely.`,
  `Outlook good.`,
  `Yes.`,
  `Signs point to yes.`,
  `Reply hazy, try again.`,
  `Ask again later.`,
  `Better not tell you now.`,
  `Cannot predict now.`,
  `Concentrate and ask again.`,
  `Don't count on it.`,
  `My reply is no.`,
  `My sources say no.`,
  `Outlook not so good.`,
  `Very doubtful.`,
  `Perhaps...`,
  `Maybe...`,
  `Sure.`,
  `I guess...`,
  `Eh, I don't know.`,
  `Maybe one day.`,
  `100%`,
  `That's gonna be a no from me big dawg.`,
  `Two thumbs up.`,
  `In the words of Lil Jon, "Yeah"`
];